# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9a02b1b170b8b6234fa7d91c1feddb02"
name = "prepurchase-tutorial"
handle = "prepurchase-tutorial-1"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "quickstart-4f74010c.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
